# Numpy Revision

####  Numpy is Python Library used for working with Arrays

#### It also has functions for working in domain of linear algebra , fourier transform , and matrices

In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.3'

In [4]:
a = np.array((1 , 2 , 3 , 4 ) )
a , type(a) , a.shape , a.ndim #ndim is dimesion

(array([1, 2, 3, 4]), numpy.ndarray, (4,), 1)

In [5]:
# 1-D array
a = np.array((1 , 2 , 3 , 4  ))
a , type(a) , a.shape , a.ndim 

(array([1, 2, 3, 4]), numpy.ndarray, (4,), 1)

In [6]:
# 0-D array
a = np.array(2)
a , type(a) , a.shape , a.ndim 

(array(2), numpy.ndarray, (), 0)

In [7]:
#2 d array
a = np.array([[1, 2 , 3 , 5],[3,45,66,4]])
a , a.shape , a.ndim

(array([[ 1,  2,  3,  5],
        [ 3, 45, 66,  4]]),
 (2, 4),
 2)

In [8]:
# 3d array

a = np.array([[[1,2,3,4], [2,3,5,67], [0,0,0,0]], [[1,34,5,0], [43,55,32,0], [0,0,0,0]]])

print(a)
print(a.shape)
print(a.ndim)

[[[ 1  2  3  4]
  [ 2  3  5 67]
  [ 0  0  0  0]]

 [[ 1 34  5  0]
  [43 55 32  0]
  [ 0  0  0  0]]]
(2, 3, 4)
3


# Array Indexing and Slicing

In [9]:
a = np.array([1, 2, 3, 4])
a[-1]

4

In [10]:
a = np.array([[1, 2, 3, 4] , [5,4,3,2]])
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [11]:
a[0,0]

1

In [12]:
a[0][-1] #-1 refers to last index
a[0 ,-1]

4

In [13]:
a[0][-1] , a[0 ,-1]

(4, 4)

In [14]:
a = np.array([[[1,2,3,4], [2,3,5,67], [0,0,0,0]], [[1,34,5,0], [43,55,32,0], [0,0,0,0]]])
a

array([[[ 1,  2,  3,  4],
        [ 2,  3,  5, 67],
        [ 0,  0,  0,  0]],

       [[ 1, 34,  5,  0],
        [43, 55, 32,  0],
        [ 0,  0,  0,  0]]])

In [15]:
a.shape  #2 rows  coloms 

(2, 3, 4)

In [16]:
a[0]

array([[ 1,  2,  3,  4],
       [ 2,  3,  5, 67],
       [ 0,  0,  0,  0]])

In [18]:
a[0][1]

array([ 2,  3,  5, 67])

In [20]:
a[0][1][2]

5

In [21]:
a[0 , : , 1:3]

array([[2, 3],
       [3, 5],
       [0, 0]])

# Numpy Data Types! 

#### i - integer
#### b - boolean
#### u - unsigned integer
#### f - float
#### c - complex float
#### m - timedelta
#### M - datetime
####  O - object
#### S- String
#### U - unicode string
#### v - fixed chunk of memory for other type (void)

In [23]:
a = np.array([1, 2, 3, 4])
a , a.dtype

(array([1, 2, 3, 4]), dtype('int32'))

In [24]:
a = np.array([1, 2, 3, 44.55])
a , a.dtype

(array([ 1.  ,  2.  ,  3.  , 44.55]), dtype('float64'))

In [25]:
a = np.array(["Apple" ,"Pakistan"])
a , a.dtype

#dtype('<U8')) tells the maximum length

(array(['Apple', 'Pakistan'], dtype='<U8'), dtype('<U8'))

In [28]:
a = np.array(["Apple" ,"Pakistan"] , dtype = "S")
a , a.dtype

(array([b'Apple', b'Pakistan'], dtype='|S8'), dtype('S8'))

In [29]:
a = np.array(["0" ,"1"] , dtype = "f")
a , a.dtype

(array([0., 1.], dtype=float32), dtype('float32'))

In [34]:
a = np.array(["0.0" ,"1.1"] , dtype = "f")
a , a.dtype

(array([0. , 1.1], dtype=float32), dtype('float32'))

In [35]:
b = a.astype("i")

In [36]:
b = a.astype("bool")

In [37]:
a

array([0. , 1.1], dtype=float32)

In [39]:
a = np.array([1, 2, 3, 44.55])
a.sort() #assending order
a

array([ 1.  ,  2.  ,  3.  , 44.55])

In [41]:
-np.sort(-a)

array([44.55,  3.  ,  2.  ,  1.  ])

In [42]:
np.sort(-a)

array([-44.55,  -3.  ,  -2.  ,  -1.  ])

# np.nan and np.inf

In [43]:
#nan is not a number and inf is infinite
np.nan

nan

In [44]:
np.nan == np.nan

False

In [45]:
np.nan == np.nan
a = np.nan
b = np.nan
a,b

(nan, nan)

In [47]:
a == b , a>b ,a<b

(False, False, False)

In [48]:
a = np.inf
b = np.inf
a,b

(inf, inf)

In [49]:
a == b , a>b

(True, False)

In [52]:
None , type(None)

(None, NoneType)

In [56]:
a = np.array([[1,2,34,4] , [2,4,66,4]] , dtype = "float")
a.shape ,a.dtype #two rows 4 colums

((2, 4), dtype('float64'))

In [57]:
a

array([[ 1.,  2., 34.,  4.],
       [ 2.,  4., 66.,  4.]])

In [62]:
a[0][1] = np.nan
a[0][2] = np.inf
a

array([[ 1., nan, inf,  4.],
       [ 2.,  4., 66.,  4.]])

In [63]:
np.isnan(a)

array([[False,  True, False, False],
       [False, False, False, False]])

In [64]:
np.isinf(a)

array([[False, False,  True, False],
       [False, False, False, False]])

# Statistical Operations

In [66]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [68]:
a.mean() , np.mean(a) , np.mean([1, 2, 3, 4]) #All are Same!

(2.5, 2.5, 2.5)

In [69]:
a.var()

1.25

In [70]:
a.std()

1.118033988749895

In [73]:
np.median(a)

2.5

In [74]:
a = np.array([[1, 2, 3, 4] , [5,4,3,2]])
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [75]:
a.mean()

3.0

In [76]:
np.mean(a)

3.0

In [77]:
np.median(a)

3.0

In [78]:
a.var()

1.5

In [79]:
a.std()

1.224744871391589

# Shape() , Reshape() , Ravel() , Flatten()!


In [80]:
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [81]:
a.ndim , a.shape

(2, (2, 4))

In [94]:
a.reshape(1,8)

array([[1, 2, 3, 4, 5, 4, 3, 2]])

In [96]:
a.ravel()

array([1, 2, 3, 4, 5, 4, 3, 2])

In [97]:
a.flatten()

array([1, 2, 3, 4, 5, 4, 3, 2])

# arrange() , linespace() , range() , random() , zeros() , and ones()

In [99]:
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [105]:
np.arange(1,11 ,dtype = "float") #or int

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [107]:
np.arange(1,11 ,3 ,dtype = "int")

array([ 1,  4,  7, 10])

In [110]:
np.linspace(1,11 ,44 ,dtype = "int")

array([ 1,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,
        4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,
        8,  9,  9,  9,  9, 10, 10, 10, 10, 11])

In [111]:
from numpy import random

In [117]:
random.randint(1,10)

2

In [119]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.zeros([6,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [123]:
np.ones([5])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [127]:
np.ones([5 ,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [128]:
np.ones([5 ,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [130]:
np.ones([5 ,2,4]).shape

(5, 2, 4)

In [131]:
np.tile([1,3,45] ,3)

array([ 1,  3, 45,  1,  3, 45,  1,  3, 45])

In [133]:
np.repeat([1,3,45] , 2)

array([ 1,  1,  3,  3, 45, 45])

# Where

In [134]:
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [136]:
np.where(a>3)

(array([0, 1, 1], dtype=int64), array([3, 0, 1], dtype=int64))

In [137]:
a.argmax()

4

# Numpy Array Read and Write

In [138]:
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [140]:
#np.save("date/a.npy" ,a)

In [143]:
#np.savetxt("date/a.npy" ,a , delimeter = " , ")

In [ ]:
#np.savez()

# Concatenate and Sorting

In [144]:
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [146]:
a.shape


(2, 4)

In [150]:
a = np.array([1,3,4,22])
b= np.array([1,43,4,22])
c = np.array([1,452,43,242])
np.concatenate([a,b,c])

array([  1,   3,   4,  22,   1,  43,   4,  22,   1, 452,  43, 242])

In [151]:
x= np.concatenate([a,b,c])

In [154]:
x.sort()
x

array([  1,   1,   1,   3,   4,   4,  22,  22,  43,  43, 242, 452])

In [156]:
b = np.array([a,c])
a,b

(array([ 1,  3,  4, 22]),
 array([[  1,   3,   4,  22],
        [  1, 452,  43, 242]]))

In [158]:
#np.concatenate([a,b])